### ISSUE TITLE
Negative quote values shown for small sending payment amounts

### ISSUE THREAD

**Issue by peterjkrey** [interledgerjs/ilp-kit#63] opened 2016-11-11 22:27 UTC
ie try to send $0.01

**Comment by vhpoet** [comment] 2016-11-16 19:07
@peterjkrey how do I reproduce this? which kits are you using?

**Comment by peterjkrey** [comment] 2016-11-16 19:26
reproduce by trying to send a very small amount ie $0.001

**Comment by vhpoet** [comment] 2016-11-16 19:40
Can't reproduce. Is this an interledger payment or a local one? what's the fee on connectors?

**Comment by peterjkrey** [comment] 2016-11-16 22:53
Appears to have been fixed - I just tested it.

**Comment by vhpoet** [comment] 2016-11-16 23:09
Closing this for now, feel free to reopen if you notice it again.

**Closed by vhpoet** 2016-11-16 23:09 UTC
