### ISSUE TITLE
wallet - when payment repeat time very low

### ISSUE THREAD

**Issue by elmurci** [interledgerjs/ilp-kit#86] opened 2016-11-26 22:27 UTC
When setting the payment repeat time very low payments fail.
Instead of retrying or failing gracefully it breaks.

```
UTION_CONDITION", "EXPIRES_DTTM", "LEDGER", "PROPOSED_DTTM", "STATUS_ID", "TRANSFER_UUID") values (DEFAULT, $1, $2, $3, $4, $5, $6) - could not serialize access due to read/write dependencies among transactions
[ledger]     at Connection.parseE (/home/javi/ilp-kit/node_modules/pg/lib/connection.js:539:11)
[ledger]     at Connection.parseMessage (/home/javi/ilp-kit/node_modules/pg/lib/connection.js:366:17)
[ledger]     at Socket.<anonymous> (/home/javi/ilp-kit/node_modules/pg/lib/connection.js:105:22)
[ledger]     at emitOne (events.js:96:13)
[ledger]     at Socket.emit (events.js:188:7)
[ledger]     at readableAddChunk (_stream_readable.js:176:18)
[ledger]     at Socket.Readable.push (_stream_readable.js:134:10)
[ledger]     at TCP.onread (net.js:548:20)
[ledger]   name: 'error',
[ledger]   length: 267,
[ledger]   severity: 'ERROR',
[ledger]   code: '40001',
[ledger]   detail: 'Reason code: Canceled on identification as a pivot, during write.',
[ledger]   hint: 'The transaction might succeed if retried.',
```

**Comment by vhpoet** [comment] 2016-12-01 00:09
@elmurci what was the repeat time on this?

**Comment by elmurci** [comment] 2016-12-01 12:40
360 ms

**Comment by michielbdejong** [comment] 2017-05-02 12:12
This sounds like a duplicate of https://github.com/interledgerjs/five-bells-ledger/issues/402 - please reopen if this is still reproducable.

**Closed by michielbdejong** 2017-05-02 12:12 UTC
Labels: bug
