### ISSUE TITLE
Balance does not auto refresh on receiving a payment

### ISSUE THREAD

**Issue by peterjkrey** [interledgerjs/ilp-kit#380] opened 2017-05-10 01:18 UTC
Page required a refresh to show balance post payment received.

**Comment by sharafian** [comment] 2017-05-10 13:36
@peterjkrey does the payment not appear in the activity log either? This might be a duplicate of https://github.com/interledgerjs/ilp-kit/issues/356

**Comment by vhpoet** [comment] 2017-05-31 15:21
dup of #356.

**Closed by vhpoet** 2017-05-31 15:21 UTC
Labels: enhancement
