### ISSUE TITLE
Peers not durable through npm reinstall

### ISSUE THREAD

**Issue by peterjkrey** [interledgerjs/ilp-kit#401] opened 2017-05-24 19:44 UTC
Appears to imply that peers are stored locally and not actually synced to database.  Peering limits appear to be same from previous install, but the peers appear offline.

This is a bug because we can not have users lose peers upon a reinstall.

![peers](https://cloud.githubusercontent.com/assets/4540878/26422043/325da1e6-407d-11e7-9af7-924bac0091f9.jpeg)

**Comment by peterjkrey** [comment] 2017-05-24 19:45
[api] 2017-05-24T19:44:46.215Z sequelize DEBUG Executing (default): SELECT "id", "type", "name", "logo", "description", "uri", "enabled", "options", "created_at", "updated_at" FROM "SettlementMethods" AS "SettlementMethod" WHERE "SettlementMethod"."enabled" = true AND "Se
ttlementMethod"."name" IS NOT NULL;
[api] 2017-05-24T19:44:46.364Z http INFO   --> GET /config 200 248ms -
[api] 2017-05-24T19:44:46.366Z connector INFO Can't get the peer limit
[api] 2017-05-24T19:44:46.366Z connector INFO Can't get the peer limit
[api] 2017-05-24T19:44:46.473Z connector INFO Can't get the peer limit
[api] 2017-05-24T19:44:46.494Z connector INFO Can't get the peer limit
[api] 2017-05-24T19:44:46.500Z socket INFO Subscribe admin
[api] 2017-05-24T19:44:46.500Z connector INFO Can't get the peer limit
[api] 2017-05-24T19:44:46.521Z connector INFO Can't get the peer limit
[api] 2017-05-24T19:44:46.543Z connector INFO Can't get the peer limit
[api] 2017-05-24T19:44:46.577Z connector INFO Can't get the peer limit
[api] 2017-05-24T19:44:46.625Z connector INFO Can't get the peer limit
[api] 2017-05-24T19:44:46.735Z connector:route-broadcaster info broadcasting 1 routes to peer.OYwSD.usd.9.0ZwLzlPLd2UWJPwYSz6RhOh3S-N-cdAhVqG62iqb6xI
[api] 2017-05-24T19:44:46.735Z connector:route-broadcaster info broadcasting 1 routes to peer.FybR-.usd.9.ncGB5ESoRkBA8iLAvLAz9EdIH2zQCTBT6Di5XPj7qFc
[api] 2017-05-24T19:44:46.736Z connector:route-broadcaster info broadcasting 1 routes to peer.OS6R4.usd.9.gqI9E_7v9XaUX95I51D6i8miDHl1Fx0Dd_WZRR9fcgI
[api] 2017-05-24T19:44:46.736Z connector:route-broadcaster info broadcasting 1 routes to peer.HULTY.usd.9.Znxdzaz2bQvgy3nJcq81JvYV-dOjMn3xBXx9qQQ0Xl4
[api] 2017-05-24T19:44:46.736Z connector:route-broadcaster info broadcasting 1 routes to peer.SUdMG.usd.9.1W78wTNgWniBxOGyzLSVFJ0HvyPbCTVy57ohGzyhwC8
[api] 2017-05-24T19:44:46.737Z connector:route-broadcaster info broadcasting 1 routes to peer.KvcJa.usd.9.8Zq10b79NO7RGHgfrX4lCXPbhVXL3Gt63SVLRH-BvR0
[api] 2017-05-24T19:44:46.737Z connector:route-broadcaster info broadcasting 1 routes to peer.eJ-cT.usd.9.RaDX8ZREv6KSi55fqCQb4cE-631PaWZaiNdAOnAFXHg
[api] 2017-05-24T19:44:46.737Z connector:route-broadcaster info broadcasting 1 routes to peer.Gw-Ll.usd.9.KRixgcBCBdyQln7IBYiopjuNO78QSFtXgOwP1sbsCSk
[api] 2017-05-24T19:44:46.737Z connector:route-broadcaster info broadcasting 1 routes to peer.Oxtp2.usd.9.Y_luxphkAy6ddYzuXb9lXxS60zg5tHjrPh8zz_BfwEA
[api] 2017-05-24T19:44:46.738Z connector:route-broadcaster info broadcasting 1 routes to peer.erKZw.usd.9.Sk0gGc3mz9_Ci2eLTTBPfuMdgFEW3hRj0QTRvWFZBEQ
[api] 2017-05-24T19:44:46.738Z connector:route-broadcaster info broadcasting 1 routes to peer.AsWzI.usd.9.MrH7ZQqiu48JEHjqE_BsE-PaMxUs8yvR0VSA8I8ZwQ8
[api] 2017-05-24T19:44:46.852Z connector:route-broadcaster info detectedDown! account: peer.SUdMG.usd.9.1W78wTNgWniBxOGyzLSVFJ0HvyPbCTVy57ohGzyhwC8 lostLedgerLinks: []
[api] 2017-05-24T19:44:46.852Z connector:route-broadcaster warn broadcasting routes to peer.SUdMG.usd.9.1W78wTNgWniBxOGyzLSVFJ0HvyPbCTVy57ohGzyhwC8 failed
[api] 2017-05-24T19:44:46.858Z connector:route-broadcaster info detectedDown! account: peer.FybR-.usd.9.ncGB5ESoRkBA8iLAvLAz9EdIH2zQCTBT6Di5XPj7qFc lostLedgerLinks: []
[api] 2017-05-24T19:44:46.858Z connector:route-broadcaster warn broadcasting routes to peer.FybR-.usd.9.ncGB5ESoRkBA8iLAvLAz9EdIH2zQCTBT6Di5XPj7qFc failed
[api] 2017-05-24T19:44:46.866Z connector:route-broadcaster info detectedDown! account: peer.OYwSD.usd.9.0ZwLzlPLd2UWJPwYSz6RhOh3S-N-cdAhVqG62iqb6xI lostLedgerLinks: []
[api] 2017-05-24T19:44:46.866Z connector:route-broadcaster warn broadcasting routes to peer.OYwSD.usd.9.0ZwLzlPLd2UWJPwYSz6RhOh3S-N-cdAhVqG62iqb6xI failed
[api] 2017-05-24T19:44:46.912Z connector INFO Can't get the peer limit
[api] 2017-05-24T19:44:46.916Z connector INFO Can't get the peer limit

**Comment by vhpoet** [comment] 2017-05-24 20:19
can't reproduce, and restarting ilp-kit fixed it for @peterjkrey, closing it for now.

**Closed by vhpoet** 2017-05-24 20:19 UTC
Labels: bug
